export interface SectorDefinition {
  id: string;
  name: string;
  category: string;
  organization: string;
  icon: string;
  accentColor: string;
  humanRoles: string[];
  physicalResources: string[];
  materials: string[];
  managementFocus: string[];
  aiPredictions: string[];
  criticalMetrics: string[];
  enabledModules: {
    schedule: boolean;
    assets: boolean;
    inventory: boolean;
    predictiveMaintenance: boolean;
    shiftManagement: boolean;
    siteAllocation: boolean;
    workload: boolean;
    analytics: boolean;
    forecasting: boolean;
    scenarios: boolean;
    pulseAI: boolean;
  };
}

export const SECTORS: SectorDefinition[] = [
  {
    id: "it_software",
    name: "IT & Software",
    category: "Software & Technology",
    organization: "TechOps Enterprise",
    icon: "💻",
    accentColor: "#38bdf8",
    humanRoles: ["Developers", "Designers", "Testers", "DevOps", "Product Managers", "Data Scientists", "Security Engineers", "Support Staff"],
    physicalResources: ["Laptops", "Servers", "Cloud Resources (AWS/GCP)", "Software Licenses", "Development Environments"],
    materials: ["API Credits", "Backup Storage Media", "Security Tokens"],
    managementFocus: ["Sprint Planning", "Project Allocation", "Skill Matching", "Developer Capacity", "Team Workload", "Sprint Velocity", "Task Assignment", "Overtime", "Project Deadlines", "License Utilization"],
    aiPredictions: ["Staffing Requirements", "Sprint Capacity", "Project Delays", "Skill Shortages", "Workload Overload", "Cloud Resource Demand"],
    criticalMetrics: ["Sprint Velocity", "Cycle Time", "Code Review Latency", "Cloud Spend / Dev", "On-Call Load"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: false,
      predictiveMaintenance: false,
      shiftManagement: true,
      siteAllocation: false,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    category: "Industrial & Production",
    organization: "Apex Manufacturing Corp",
    icon: "🏭",
    accentColor: "#f97316",
    humanRoles: ["Operators", "Mechanical Engineers", "Plant Supervisors", "Technicians", "Quality Inspectors", "Safety Officers"],
    physicalResources: ["CNC Machines", "Assembly Production Lines", "Robotic Arms", "Tooling Rigs", "Forklifts", "Injection Molders"],
    materials: ["Raw Steel & Aluminum", "Polymers", "Fasteners", "Spare Bearings", "Lubricants & Coolant"],
    managementFocus: ["Machine Utilization", "Production Capacity", "Downtime Prevention", "OEE Tracking", "Maintenance Windows", "Production Targets", "Material Consumption", "Shift Workload"],
    aiPredictions: ["Predictive Machine Downtime", "Maintenance Intervals", "Production Demand Volatility", "Material Shortage Alerts", "Workforce Shift Needs", "Capacity Bottlenecks"],
    criticalMetrics: ["OEE (Overall Equipment Effectiveness)", "Mean Time To Repair (MTTR)", "Scrap Rate", "Line Throughput", "Unit Production Cost"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "construction",
    name: "Construction",
    category: "Infrastructure & Built Environment",
    organization: "Metro Build Infra",
    icon: "🏗️",
    accentColor: "#eab308",
    humanRoles: ["Civil Engineers", "Architects", "Heavy Equipment Operators", "Site Supervisors", "General Contractors", "Safety Inspectors"],
    physicalResources: ["Tower Cranes", "Hydraulic Excavators", "Dump Trucks", "Concrete Mixers", "Scaffolding Rigs", "Power Generators"],
    materials: ["Portland Cement", "Structural Steel & Rebar", "Coarse Sand", "Bricks & Blocks", "Aggregates", "Pipes"],
    managementFocus: ["Project Phase Gantt", "Jobsite Asset Allocation", "Subcontractor Capacity", "Safety Compliance", "Weather Contingency", "Stage Gate Approvals"],
    aiPredictions: ["Bulk Material Shortages", "Heavy Equipment Conflicts", "Site Labor Shortfalls", "Milestone Slippage Risks", "Cost Overruns", "Weather Impact Cascades"],
    criticalMetrics: ["Schedule Performance Index (SPI)", "Cost Performance Index (CPI)", "Equipment Idle Rate", "Site Safety Incident Rate", "Material Wastage"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "healthcare",
    name: "Healthcare",
    category: "Medical & Life Sciences",
    organization: "General Health System",
    icon: "🏥",
    accentColor: "#ef4444",
    humanRoles: ["Physicians & Specialists", "Registered Nurses", "Clinical Technicians", "Radiologists", "Pharmacists", "Administrative Coordinators"],
    physicalResources: ["Inpatient Beds", "ICU Isolation Beds", "Operating Rooms", "Emergency Bays", "Ventilators", "MRI / CT Scanners", "Ultrasound Units"],
    materials: ["Medical Gases (O2)", "Personal Protective Equipment", "Surgical Packs", "Pharmaceuticals", "Sterile Disposables"],
    managementFocus: ["Shift Rostering", "Patient Admission Capacity", "Bed Occupancy Ratios", "Surgical Theater Scheduling", "Sterilization Windows", "Nurse-to-Patient Ratios"],
    aiPredictions: ["Surge Patient Demand", "ICU Bed Shortfall", "Clinical Staffing Deficits", "Diagnostic Equipment Bottlenecks", "Seasonal Peak Admission Periods"],
    criticalMetrics: ["Bed Turnover Rate", "Nurse Staffing Equilibrium", "OR Utilization %", "Emergency Room Wait Time", "Critical Device Availability"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "education",
    name: "Education",
    category: "Higher Education & Research",
    organization: "National University System",
    icon: "🎓",
    accentColor: "#8b5cf6",
    humanRoles: ["Professors", "Lecturers", "Teaching Assistants", "Lab Demonstrators", "Academic Advisors", "Department Chairs"],
    physicalResources: ["Lecture Halls", "Computer Labs", "Science Laboratories", "Campus Libraries", "Audiovisual Suites", "Research Clusters"],
    materials: ["Lab Reagents", "Computing Terminals", "Course Textbooks & Licenses", "Stationery & Consumables"],
    managementFocus: ["Timetable Conflict Resolution", "Faculty Teaching Hours", "Classroom Capacity Allocations", "Lab Schedule Synchronization", "Student Enrollment Caps"],
    aiPredictions: ["Classroom Capacity Crunches", "Faculty Workload Imbalance", "Student Enrollment Surges", "Laboratory Equipment Bottlenecks", "Exam Room Conflicts"],
    criticalMetrics: ["Faculty Utilization", "Classroom Seat Fill Rate", "Lab Equipment Utilization", "Course Completion Rate", "Timetable Conflict Count"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: false,
      shiftManagement: false,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "logistics",
    name: "Logistics & Transportation",
    category: "Supply Chain & Fleet",
    organization: "TransGlobal Freight & Logistics",
    icon: "🚚",
    accentColor: "#06b6d4",
    humanRoles: ["Long-haul Drivers", "Fleet Dispatchers", "Warehouse Operators", "Route Planners", "Fleet Mechanics", "Logistics Supervisors"],
    physicalResources: ["Semi-Trucks", "Cargo Delivery Vans", "Electric Forklifts", "Pallet Jacks", "Refrigerated Containers", "Distribution Hubs"],
    materials: ["Diesel & EV Fleet Power", "Packaging Materials", "Pallets & Strapping", "Tires & Engine Oil"],
    managementFocus: ["Vehicle Utilization %", "Driver Shift & Rest Compliance", "Multi-Stop Route Balancing", "Hub Loading Dock Capacity", "Maintenance Windows"],
    aiPredictions: ["Peak Delivery Surge Demand", "Fleet Sizing Requirements", "Fuel Consumption Trends", "Predictive Fleet Maintenance", "Delivery Route Bottlenecks"],
    criticalMetrics: ["On-Time In-Full (OTIF)", "Fleet Fleet Utilization %", "Cost per Ton-Mile", "Idle Time / Route", "Driver Hours of Service Compliance"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "retail",
    name: "Retail",
    category: "Commerce & Store Operations",
    organization: "OmniStore Retail Network",
    icon: "🛍️",
    accentColor: "#ec4899",
    humanRoles: ["Store Managers", "Department Supervisors", "Cashiers", "Merchandisers", "Stock Clerks", "Customer Care Reps"],
    physicalResources: ["Retail Outlets", "POS Checkouts", "Shelving & Display Endcaps", "Handheld Barcode Scanners", "Backroom Storage Racks"],
    materials: ["Store Merchandise", "Receipt Rolls & Bags", "Promo Signage", "Cleaning Supplies"],
    managementFocus: ["Shift Scheduling", "Peak Footfall Staffing", "Stock Replenishment", "Checkout Wait Time Reduction", "Promotional Campaign Staffing"],
    aiPredictions: ["Seasonal Footfall Demand", "Inventory Reorder Dates", "Cashier Overtime Requirements", "Floor Staff Workload Spikes", "Stockout Risk on Top SKUs"],
    criticalMetrics: ["Sales per Labor Hour", "Checkout Throughput", "Inventory Shrinkage", "Stockout Rate", "Staff Turnover"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: false,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "hospitality",
    name: "Hospitality",
    category: "Travel & Hotels",
    organization: "Grand Horizon Resorts",
    icon: "🏨",
    accentColor: "#10b981",
    humanRoles: ["General Managers", "Front Desk Agents", "Executive Chefs", "Line Cooks", "Housekeeping Leads", "Concierge Staff"],
    physicalResources: ["Hotel Suites", "Banquet Halls", "Commercial Kitchen Ranges", "Laundry Industrial Presses", "Guest Shuttles", "Event Stages"],
    materials: ["Linens & Bedding", "Culinary Ingredients", "Beverage Stock", "Toiletries & Guest Amenities", "Sanitization Chemicals"],
    managementFocus: ["Occupancy Rate Balancing", "Housekeeping Turnaround Time", "Kitchen Shift Rostering", "Event Resource Staging", "Room Maintenance Cycles"],
    aiPredictions: ["Seasonal Occupancy Peaks", "Weekend Staffing Deficits", "F&B Inventory Depletion", "Peak Room Turnover Load", "Utility Usage Spikes"],
    criticalMetrics: ["RevPAR (Revenue Per Available Room)", "Average Daily Rate (ADR)", "Housekeeping Cleaning Minutes / Room", "Food Waste Ratio", "Guest Service Response Time"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "banking_finance",
    name: "Banking & Finance",
    category: "Financial Services & Operations",
    organization: "Sterling Financial Group",
    icon: "🏦",
    accentColor: "#6366f1",
    humanRoles: ["Branch Managers", "Loan Officers", "Financial Analysts", "Compliance Officers", "Tellers", "IT Security Engineers"],
    physicalResources: ["Branch Offices", "Automated Teller Machines (ATMs)", "Cash Vaults", "Trading Terminals", "Secure Servers", "Call Center Hubs"],
    materials: ["Secure Card Stock", "Chequebooks", "Hardware Security Keys", "Statement Stationery"],
    managementFocus: ["Branch Footfall Rostering", "ATM Cash Balancing & Uptime", "Underwriting Queue Processing", "Compliance Audit Readiness", "Core System Availability"],
    aiPredictions: ["Customer Service Demand", "Loan Processing Bottlenecks", "Branch Teller Capacity Needs", "ATM Cash Refill Timing", "Peak Transaction Surges"],
    criticalMetrics: ["Transaction Processing SLA", "Cost per Transaction", "Branch Utilization %", "Audit Compliance Score", "Queue Wait Time"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: false,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "government",
    name: "Government",
    category: "Public Sector & Civic Services",
    organization: "Civic Public Administration",
    icon: "🏛️",
    accentColor: "#64748b",
    humanRoles: ["Department Directors", "Policy Analysts", "Public Inspectors", "Civil Service Clerks", "Social Case Workers", "Field Technicians"],
    physicalResources: ["Civic Centers", "Public Vehicle Fleets", "Inspection Vehicles", "Municipal Facilities", "Emergency Response Hubs"],
    materials: ["Permit Forms & Documentation", "Emergency Supplies", "Municipal Utility Equipment", "Road Maintenance Asphalt"],
    managementFocus: ["Public Program Allocation", "Fiscal Budget Consumption", "Citizen Application Backlog", "Inter-Department Field Sharing", "Audit Trail Verification"],
    aiPredictions: ["Permit Application Backlog Surges", "Public Budget Depletion Timelines", "Civic Staffing Deficits", "Municipal Vehicle Maintenance", "Emergency Asset Readiness"],
    criticalMetrics: ["Citizen Case Resolution Days", "Budget Execution Variance", "Audit Compliance %", "Public Fleet Availability", "Service Availability Index"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "agriculture",
    name: "Agriculture",
    category: "AgriTech & Farming",
    organization: "Verdant Fields Agricultural Ops",
    icon: "🌾",
    accentColor: "#84cc16",
    humanRoles: ["Agronomists", "Farm Managers", "Tractor Operators", "Irrigation Specialists", "Harvest Crew", "Quality Inspectors"],
    physicalResources: ["Agricultural Land Parcs", "Tractors & Combines", "Automated Drip Irrigation Systems", "Grain Storage Silos", "Drying Facilities", "Cold Stores"],
    materials: ["Certified Seeds", "Organic & NPK Fertilizer", "Irrigation Water (m³)", "Crop Protection Solutions", "Fuel (Diesel)"],
    managementFocus: ["Acreage Utilization", "Crop Rotation Scheduling", "Irrigation Cycle Management", "Harvest Window Optimization", "Equipment Fuel Efficiency"],
    aiPredictions: ["Seasonal Workforce Demand", "Water Consumption Demand", "Yield Prediction Variance", "Predictive Harvester Maintenance", "Fertilizer Depletion Schedule"],
    criticalMetrics: ["Yield per Hectare", "Water Use Efficiency (L/kg)", "Tractor Operating Hours / Acre", "Post-Harvest Loss %", "Soil Quality Index"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "energy_utilities",
    name: "Energy & Utilities",
    category: "Power, Water & Grid Ops",
    organization: "Global Grid Energy System",
    icon: "⚡",
    accentColor: "#f59e0b",
    humanRoles: ["Power Plant Operators", "Electrical Engineers", "Linemen & Field Crews", "Substation Technicians", "Control Room Dispatchers", "Safety Engineers"],
    physicalResources: ["Power Generation Turbines", "High-Voltage Substations", "Utility Service Trucks", "Wind Turbines", "Solar Arrays", "Grid Transformers"],
    materials: ["Turbine Lubricants", "Replacement Insulators", "Switchgear Components", "Copper Cables", "Transformer Oil"],
    managementFocus: ["Peak Generation Capacity", "Substation Maintenance Outages", "Grid Load Balancing", "Emergency Storm Crew Dispatch", "Asset Life Cycle Management"],
    aiPredictions: ["Grid Peak Load Surges", "Transformer Failure Probability", "Field Crew Emergency Requirements", "Turbine Maintenance Scheduling", "Capacity Degradation"],
    criticalMetrics: ["SAIDI (Outage Duration)", "SAIFI (Outage Frequency)", "Plant Availability Factor", "Heat Rate / Efficiency", "Unplanned Downtime Hours"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "telecom",
    name: "Telecom",
    category: "Telecommunications & Networks",
    organization: "NextWave Cellular & Fiber",
    icon: "📡",
    accentColor: "#0284c7",
    humanRoles: ["Tower Riggers", "Network Engineers", "Fiber Optic Splicers", "Field Dispatch Technicians", "NOC Analysts", "RF Engineers"],
    physicalResources: ["Cellular Towers", "Fiber Splicing Vans", "Microwave Antennas", "Central Office Switches", "Emergency Diesel Generators"],
    materials: ["Fiber Optic Spools", "Coaxial Cables", "Connectors & Enclosures", "Backup Batteries", "Mast Hardware"],
    managementFocus: ["Cell Tower Maintenance", "Network Outage Restoration SLA", "Field Service Dispatching", "Fiber Rollout Project Tracking", "Spectrum Asset Management"],
    aiPredictions: ["Traffic Congestion by Region", "Tower Power Outage Risks", "Fiber Repair Field Tech Demand", "Hardware Degradation Timelines", "Coverage Expansion Capacity"],
    criticalMetrics: ["Network Uptime (99.999%)", "MTTR for Fiber Cuts", "First-Time Fix Rate", "Technician Utilization", "Site Power Resilience Score"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "aviation",
    name: "Aviation",
    category: "Aerospace & Airline Operations",
    organization: "AeroWings Flight Operations",
    icon: "✈️",
    accentColor: "#3b82f6",
    humanRoles: ["Captains & First Officers", "Cabin Crew Members", "Aircraft Maintenance Engineers (AME)", "Ground Handling Crew", "Flight Dispatchers", "Baggage Handlers"],
    physicalResources: ["Commercial Aircraft", "Airport Departure Gates", "Ground Power Units (GPU)", "Jet Bridges", "Pushback Tugs", "Baggage Conveyors"],
    materials: ["Aviation Jet A-1 Fuel", "Hydraulic Fluids", "Tires & Brake Assemblies", "In-flight Catering Stock", "De-icing Fluid"],
    managementFocus: ["Crew Flight Duty Period Compliance", "Aircraft Turnaround Time", "A/B/C/D Maintenance Checks", "Gate Assignment Balancing", "Baggage Handling Flow"],
    aiPredictions: ["Flight Turnaround Bottlenecks", "Mandatory Maintenance Window Collisions", "Cabin Crew Duty Limit Expirations", "Fuel Consumption Spikes", "Ground Equipment Conflicts"],
    criticalMetrics: ["On-Time Departure Rate (D0)", "Aircraft Ground Turnaround Time", "Maintenance Dispatch Reliability", "Crew Duty Utilization", "Fuel Burn Efficiency"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "automotive",
    name: "Automotive",
    category: "Automotive Manufacturing & Assembly",
    organization: "Veloce Motor Works",
    icon: "🚗",
    accentColor: "#dc2626",
    humanRoles: ["Assembly Line Workers", "Robotics Technicians", "Quality Control Engineers", "Logistics Handlers", "Paint Shop Technicians", "Plant Managers"],
    physicalResources: ["Chassis Press Lines", "Automated Weld Robots", "Paint Shop Booths", "Final Assembly Conveyors", "Dynamometer Test Cells"],
    materials: ["Sheet Metal Stampings", "Wire Harnesses", "Powertrains & Motors", "Automotive Glazing & Glass", "Fasteners & Adhesives"],
    managementFocus: ["Line Takt Time", "Robot Uptime & Calibration", "Paint Shop Batching", "Component Just-In-Time (JIT) Delivery", "Defect Prevention"],
    aiPredictions: ["Production Line Bottlenecks", "Welding Robot Wear & Tear", "Supply Chain Part Deficits", "Overtime Requirements by Line", "Quality Failure Forecasts"],
    criticalMetrics: ["Takt Time vs Target", "First-Time Through Quality (FTTQ)", "Press Line Availability", "Units Produced per Shift", "Work-In-Progress (WIP) Volume"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "research_development",
    name: "Research & Development",
    category: "Science, Innovation & Labs",
    organization: "NexSys Advanced Labs",
    icon: "🔬",
    accentColor: "#a855f7",
    humanRoles: ["Principal Investigators", "Postdoctoral Researchers", "Lab Technicians", "Data Scientists", "Research Fellows", "Grant Managers"],
    physicalResources: ["Cleanrooms", "Spectrometers & Mass Analyzers", "Cryogenic Storage", "High-Performance Compute Clusters", "Prototyping Facilities"],
    materials: ["Chemical Reagents", "Silicon Wafers", "Rare Gases", "Cell Culture Media", "Precision Substrates"],
    managementFocus: ["Grant Budget Depletion", "Specialized Instrument Booking", "Experiment Milestone Tracking", "Multi-Disciplinary Team Allocation", "IP Milestone Delivery"],
    aiPredictions: ["Instrument Booking Contention", "Grant Runway Depletion Dates", "Researcher Bandwidth Bottlenecks", "Reagent Supply Expirations", "Milestone Slip Risks"],
    criticalMetrics: ["Instrument Utilization %", "Grant Burn Rate", "Milestone Delivery Adherence", "Publication & Patent Velocity", "Experiment Cycle Time"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: false,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "media_entertainment",
    name: "Media & Entertainment",
    category: "Film, Broadcast & Content Production",
    organization: "Aether Studios Production",
    icon: "🎬",
    accentColor: "#f43f5e",
    humanRoles: ["Directors & Producers", "Cinematographers (DP)", "Sound Engineers", "Video Editors", "VFX Artists", "Production Managers"],
    physicalResources: ["Soundstages & Studios", "Cinema Camera Packages", "Lighting Rigs & Grip Trucks", "Color Grading Suites", "Render Farms"],
    materials: ["High-Speed NVMe Storage Media", "Set Construction Materials", "Wardrobe & Props", "Grip Expendables & Gaffer Tape"],
    managementFocus: ["Call Sheet Scheduling", "Studio Floor Availability", "Post-Production Milestones", "Equipment Rental Timelines", "Crew Overtime Management"],
    aiPredictions: ["Post-Production Crunch Periods", "Studio Space Booking Collisions", "VFX Render Compute Shortfalls", "Crew Overtime Cost Spikes", "Release Date Slips"],
    criticalMetrics: ["Pages / Shots Shot per Day", "Budget Variance vs Actuals", "Post-Production Velocity", "Render Farm Queue Latency", "Crew Turnaround Hours"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: false,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "professional_services",
    name: "Professional Services",
    category: "Consulting, Legal & Advisory",
    organization: "Beacon Advisory Group",
    icon: "👔",
    accentColor: "#0ea5e9",
    humanRoles: ["Managing Partners", "Senior Consultants", "Engagement Managers", "Business Analysts", "Legal Associates", "Subject Matter Experts"],
    physicalResources: ["Client Engagement Rooms", "Encrypted Cloud Data Rooms", "Audit Testing Labs", "Video Conference Centers"],
    materials: ["Licensed Proprietary Benchmarks", "Printing & Briefing Binders", "Specialized Research Subscriptions"],
    managementFocus: ["Consultant Billable Utilization", "Engagement Margin Management", "Skill & Subject Matter Matching", "Client Deliverable Deadlines", "Travel Scheduling"],
    aiPredictions: ["Consultant Burnout / Over-allocation", "Bench Capacity & Idle Periods", "Project Scope Creep Impact", "Staffing Deficits on Major Proposals", "Revenue Realization Delays"],
    criticalMetrics: ["Billable Utilization Rate", "Realization Rate", "Revenue per Partner", "Bench Strength / Idle %", "Engagement Gross Margin"],
    enabledModules: {
      schedule: true,
      assets: false,
      inventory: false,
      predictiveMaintenance: false,
      shiftManagement: false,
      siteAllocation: false,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "warehousing",
    name: "Warehousing",
    category: "Storage, Fulfillment & Distribution",
    organization: "Pinnacle Fulfillment Hub",
    icon: "📦",
    accentColor: "#78716c",
    humanRoles: ["Warehouse Managers", "Inbound Receivers", "Forklift Drivers", "Order Pickers", "Packers", "Inventory Controllers"],
    physicalResources: ["High-Bay Racks", "Automated Guided Vehicles (AGV)", "Conveyor Sorter Systems", "Stretch Wrappers", "Dock Levelers"],
    materials: ["Shipping Cartons", "Bubble Wrap & Air Pillows", "Packing Tape", "Shipping Labels", "Wooden Pallets"],
    managementFocus: ["Storage Cube Utilization", "Picking Path Optimization", "Dock Door Scheduling", "Shift Balancing", "Order Fulfillment Cycle Time"],
    aiPredictions: ["Holiday Fulfillment Peak Demand", "Slotting Capacity Exhaustion", "Forklift Battery / Mechanical Failures", "Packing Material Stockouts", "Overtime Spikes"],
    criticalMetrics: ["Units Picked per Hour (UPH)", "Dock-to-Stock Time", "Order Accuracy %", "Warehouse Cube Utilization %", "Inventory Turnover"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "mining",
    name: "Mining",
    category: "Extraction, Minerals & Heavy Resources",
    organization: "Titan Ore & Mineral Mining",
    icon: "⛏️",
    accentColor: "#d97706",
    humanRoles: ["Mining Engineers", "Haul Truck Drivers", "Geologists", "Drill & Blast Technicians", "Heavy Diesel Mechanics", "Site Safety Officers"],
    physicalResources: ["Ultra-Class Haul Trucks", "Hydraulic Mining Shovels", "Rotary Blast Hole Drills", "Primary Rock Crushers", "Conveyor Belt Overlands"],
    materials: ["Industrial Explosives & Detonators", "Crusher Liners & Wear Plates", "Heavy Diesel Fuel", "Drill Bits", "Dust Suppression Water"],
    managementFocus: ["Fleet Dispatch Synchronization", "Crusher Feed Rate", "Haul Road Maintenance", "Shift Changeover Optimization", "Safety Compliance & Dust Levels"],
    aiPredictions: ["Haul Truck Tire & Engine Failures", "Crusher Bottleneck Surges", "Fuel Consumption Inefficiencies", "Ore Grade Dilution Risks", "Shift Operator Fatigue Alerts"],
    criticalMetrics: ["Tons Moved per Hour", "Equipment Mechanical Availability", "Fuel Burn per Ton", "Safety Zero-Harm Compliance", "Haul Cycle Time"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
  {
    id: "general_custom",
    name: "General / Custom",
    category: "Universal Multi-Purpose Enterprise",
    organization: "Enterprise Operations",
    icon: "🌐",
    accentColor: "#38bdf8",
    humanRoles: ["Team Leads", "Specialists", "Coordinators", "Operations Managers", "Analysts", "Technicians"],
    physicalResources: ["Facilities", "Equipment", "Vehicles", "Hardware Terminals", "Infrastructure"],
    materials: ["Supplies", "Consumables", "Inventory Stock", "Components"],
    managementFocus: ["Resource Availability", "Task Execution", "Budget Control", "Capacity Equilibrium", "Milestone Tracking"],
    aiPredictions: ["Workload Imbalances", "Project Delays", "Resource Exhaustion", "Future Demand Surges", "Capacity Bottlenecks"],
    criticalMetrics: ["Resource Utilization", "Capacity Margin", "Delivery Time", "Budget Adherence", "Health Index"],
    enabledModules: {
      schedule: true,
      assets: true,
      inventory: true,
      predictiveMaintenance: true,
      shiftManagement: true,
      siteAllocation: true,
      workload: true,
      analytics: true,
      forecasting: true,
      scenarios: true,
      pulseAI: true,
    },
  },
];
