import { ResourceItem } from "@/components/ResourcesView";

export interface SectorDefinition {
  id: string;
  name: string;
  category: string;
  organization: string;
  icon: string;
  accentColor: string;
  criticalPathProduct: string;
  incidentTitle: string;
  incidentDetail: string;
  incidentDelay: string;
  incidentCost: string;
  systemHealth: string;
  uptime: string;
  atRiskCapacity: string;
  forecastConfidence: string;
  openDecisions: string;
  resources: ResourceItem[];
}

export const SECTORS: SectorDefinition[] = [
  {
    id: "fintech",
    name: "FinTech & Cloud Software",
    category: "Software & Technology",
    organization: "Northstar Ops",
    icon: "💻",
    accentColor: "#38bdf8",
    criticalPathProduct: "Payment Gateway v2.4",
    incidentTitle: "Release at Risk: 60% QA Bandwidth Shortfall",
    incidentDetail:
      "A 60% drop in QA automated test capacity has blocked Mobile Core E2E Testing (+18h), cascading into Payment Gateway v2.4 (+32h). Unmitigated, Sprint 44 RC freeze slips by +3.8 calendar days with $4,200 in overtime.",
    incidentDelay: "+3.8 Days",
    incidentCost: "$4,200",
    systemHealth: "87.4%",
    uptime: "99.98%",
    atRiskCapacity: "12.6h (Mobile Core QA)",
    forecastConfidence: "94.2%",
    openDecisions: "4 decisions · 2 pending",
    resources: [
      {
        id: "RES-01",
        name: "Arjun Rao",
        role: "Senior QA Automation Engineer",
        type: "People",
        status: "Unavailable",
        utilization: 96,
        project: "Support Pod",
        skills: ["Mobile QA", "Appium", "Jest", "CI/CD"],
        costRate: "$85/h",
        risk: "High",
        avatarText: "AR",
        avatarBg: "from-blue-600 to-cyan-500",
        upcoming: "Mobile Release Train Test Cycle (Proposed)",
        constraints: "Max 40h/week, PTO scheduled next Thursday",
      },
      {
        id: "RES-02",
        name: "Priya Sharma",
        role: "Staff Backend Engineer",
        type: "People",
        status: "High Load",
        utilization: 88,
        project: "Northstar Core API",
        skills: ["Go", "gRPC", "PostgreSQL", "Kafka"],
        costRate: "$110/h",
        risk: "Medium",
        avatarText: "PS",
        avatarBg: "from-indigo-600 to-blue-500",
        upcoming: "Payment Gateway Refactor",
        constraints: "Core database lock-in until Sprint 44 freeze",
      },
      {
        id: "RES-03",
        name: "Marcus Vance",
        role: "Cloud DevOps Architect",
        type: "People",
        status: "Available",
        utilization: 64,
        project: "Northstar Onboarding",
        skills: ["Kubernetes", "AWS EKS", "Terraform", "ArgoCD"],
        costRate: "$105/h",
        risk: "Low",
        avatarText: "MV",
        avatarBg: "from-emerald-600 to-teal-500",
        upcoming: "Production Cluster Autoscaling Tuning",
        constraints: "On-call primary rotation starts Friday",
      },
      {
        id: "RES-04",
        name: "Elena Rostova",
        role: "Senior UI/UX Specialist",
        type: "People",
        status: "Available",
        utilization: 70,
        project: "Design System 2.0",
        skills: ["Figma", "Design Tokens", "React UI", "Accessibility"],
        costRate: "$90/h",
        risk: "Low",
        avatarText: "ER",
        avatarBg: "from-purple-600 to-pink-500",
        upcoming: "Mobile Checkout Design Review",
        constraints: "Leading enterprise usability sprint tomorrow",
      },
      {
        id: "RES-05",
        name: "GPU Cluster Alpha",
        role: "4x NVIDIA H100 SXM5 Nodes",
        type: "Equipment",
        status: "High Load",
        utilization: 98,
        project: "Simulation Engine",
        skills: ["CUDA", "PyTorch", "Monte-Carlo Inference"],
        costRate: "$24/h",
        risk: "High",
        avatarText: "GPU",
        avatarBg: "from-emerald-500 to-teal-600",
        upcoming: "Scheduled node maintenance in 72 hours",
        constraints: "Requires 12h cool-down cycle if load > 95%",
      },
      {
        id: "RES-06",
        name: "Test Lab Alpha",
        role: "Physical Device Farm (32 Devices)",
        type: "Equipment",
        status: "Available",
        utilization: 50,
        project: "Mobile Automation",
        skills: ["iOS 18", "Android 15", "Biometric Hardware Emulation"],
        costRate: "$12/h",
        risk: "Low",
        avatarText: "LAB",
        avatarBg: "from-amber-500 to-orange-600",
        upcoming: "16 slots unallocated for regression run",
        constraints: "Network throughput throttled past 200 req/sec",
      },
      {
        id: "RES-07",
        name: "Sprint Contingency Reserve",
        role: "Emergency Reallocation Capital",
        type: "Budget",
        status: "Available",
        utilization: 42,
        project: "Northstar Governance",
        skills: ["Overtime Funding", "Expedited Contractor Sourcing"],
        costRate: "$1,200",
        risk: "Low",
        avatarText: "USD",
        avatarBg: "from-green-600 to-emerald-500",
        upcoming: "$696 unallocated buffer available",
        constraints: "Requires VP approval if single draw > $2,000",
      },
      {
        id: "RES-08",
        name: "Shared Redis Cache Cluster",
        role: "High-Throughput Session Store",
        type: "Shared",
        status: "High Load",
        utilization: 84,
        project: "Payment Core",
        skills: ["Cluster Sharding", "Sub-millisecond Latency"],
        costRate: "$18/h",
        risk: "Medium",
        avatarText: "RDC",
        avatarBg: "from-red-600 to-rose-500",
        upcoming: "Memory optimization sweep queued",
        constraints: "Max memory ceiling 64GB before eviction begins",
      },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare & Clinical Operations",
    category: "Medical & Health",
    organization: "Metro General Hospital",
    icon: "🏥",
    accentColor: "#10b981",
    criticalPathProduct: "Emergency Surgical Schedule & ICU",
    incidentTitle: "OR 3 at Risk: Chief Surgeon & Anesthesiologist Shortfall",
    incidentDetail:
      "A sudden surgical staff illness has created an 8.4h deficit in Operating Theater 3. Downstream, ICU bed clearance is blocked (+16h), delaying 6 scheduled elective surgeries and risking emergency trauma overflow with $18,500 in standby costs.",
    incidentDelay: "+2.1 Days",
    incidentCost: "$18,500",
    systemHealth: "91.2%",
    uptime: "99.99%",
    atRiskCapacity: "8.4h (OR Surgical Suite 3)",
    forecastConfidence: "96.4%",
    openDecisions: "3 decisions · 1 urgent",
    resources: [
      {
        id: "HC-01",
        name: "Dr. Arjun Rao",
        role: "Chief Orthopedic Trauma Surgeon",
        type: "People",
        status: "Unavailable",
        utilization: 95,
        project: "Trauma Ward A",
        skills: ["Orthopedic Surgery", "Emergency Trauma", "Arthroscopy"],
        costRate: "$280/h",
        risk: "High",
        avatarText: "AR",
        avatarBg: "from-emerald-600 to-teal-500",
        upcoming: "Scheduled 4-hour spinal fusion procedure",
        constraints: "Max 12h surgical shift limit per state board",
      },
      {
        id: "HC-02",
        name: "Dr. Priya Sharma",
        role: "Staff Pediatric Anesthesiologist",
        type: "People",
        status: "High Load",
        utilization: 86,
        project: "Pediatric Surgery Wing",
        skills: ["Pediatric Anesthesia", "Cardiac Monitoring", "Intensive Care"],
        costRate: "$250/h",
        risk: "Medium",
        avatarText: "PS",
        avatarBg: "from-cyan-600 to-blue-500",
        upcoming: "OR 2 Heart Valve Repair standby",
        constraints: "Requires 8h rest between emergency callouts",
      },
      {
        id: "HC-03",
        name: "Dr. Marcus Vance",
        role: "Cardiovascular Perfusionist",
        type: "People",
        status: "Available",
        utilization: 62,
        project: "Cardiology Suite",
        skills: ["Heart-Lung Machine", "ECMO", "Cardiopulmonary Bypass"],
        costRate: "$195/h",
        risk: "Low",
        avatarText: "MV",
        avatarBg: "from-teal-600 to-emerald-500",
        upcoming: "Routine bypass machine diagnostics",
        constraints: "On-call emergency transplant team starts Friday",
      },
      {
        id: "HC-04",
        name: "Nurse Elena Rostova",
        role: "Head ICU Charge Nurse",
        type: "People",
        status: "Available",
        utilization: 68,
        project: "ICU Unit 4",
        skills: ["Ventilator Management", "Patient Triage", "Critical Care"],
        costRate: "$95/h",
        risk: "Low",
        avatarText: "ER",
        avatarBg: "from-blue-600 to-indigo-500",
        upcoming: "ICU Bed turnover protocol review",
        constraints: "Oversees 14 active patient beds",
      },
      {
        id: "HC-05",
        name: "Operating Theater 3",
        role: "Laminar Flow Sterile Surgical Suite",
        type: "Equipment",
        status: "High Load",
        utilization: 94,
        project: "Orthopedic Surgery",
        skills: ["Sterile Filtration", "Surgical Robots", "Telemetry Monitors"],
        costRate: "$450/h",
        risk: "High",
        avatarText: "OR3",
        avatarBg: "from-rose-600 to-red-500",
        upcoming: "Sterilization cycle in 6 hours",
        constraints: "Requires 45m decontamination between patients",
      },
      {
        id: "HC-06",
        name: "MRI Scanner Suite Alpha",
        role: "3.0T High-Resolution MRI Unit",
        type: "Equipment",
        status: "Available",
        utilization: 58,
        project: "Radiology Department",
        skills: ["Neurological Imaging", "Musculoskeletal Scan"],
        costRate: "$180/h",
        risk: "Low",
        avatarText: "MRI",
        avatarBg: "from-indigo-500 to-cyan-600",
        upcoming: "4 diagnostic scan slots open today",
        constraints: "Cryogen helium level inspection due Thursday",
      },
      {
        id: "HC-07",
        name: "Clinical Emergency Reserve",
        role: "Contingency Physician Sourcing Fund",
        type: "Budget",
        status: "Available",
        utilization: 38,
        project: "Hospital Administration",
        skills: ["Locum Tenens Doctors", "Emergency Overtime"],
        costRate: "$5,000",
        risk: "Low",
        avatarText: "MED",
        avatarBg: "from-emerald-500 to-teal-700",
        upcoming: "$3,100 buffer unspent",
        constraints: "Requires Chief Medical Officer sign-off",
      },
      {
        id: "HC-08",
        name: "Central Blood Bank & Plasma Pool",
        role: "Universal Donor O-Neg Reserve",
        type: "Shared",
        status: "High Load",
        utilization: 82,
        project: "Blood Center",
        skills: ["Packed Red Blood Cells", "Platelets", "Cryoprecipitate"],
        costRate: "$65/unit",
        risk: "Medium",
        avatarText: "BLD",
        avatarBg: "from-red-600 to-amber-600",
        upcoming: "Regional blood drive scheduled tomorrow",
        constraints: "Shelf-life perishable within 28 days",
      },
    ],
  },
  {
    id: "retail",
    name: "Retail & E-Commerce Logistics",
    category: "Supply Chain & Retail",
    organization: "Apex Logistics Hub",
    icon: "🛍️",
    accentColor: "#f59e0b",
    criticalPathProduct: "Black Friday 2-Day Guaranteed Delivery",
    incidentTitle: "Fulfillment at Risk: 40% Warehouse Shift Deficit",
    incidentDetail:
      "A 40% automated sorting conveyor slowdown and staff shortage at Hub Alpha has created a 1,400 package backlog (+14h). Downstream dispatch to delivery fleets is blocked, risking 2,800 missed 2-day delivery SLAs and $22,000 in customer refunds.",
    incidentDelay: "+1.9 Days",
    incidentCost: "$22,000",
    systemHealth: "84.2%",
    uptime: "99.85%",
    atRiskCapacity: "1,400 pkgs/hr (Hub Alpha)",
    forecastConfidence: "93.1%",
    openDecisions: "5 decisions · 3 urgent",
    resources: [
      {
        id: "RT-01",
        name: "Arjun Rao",
        role: "Shift Logistics Director",
        type: "People",
        status: "Unavailable",
        utilization: 94,
        project: "Hub Alpha Sorting Line",
        skills: ["Warehouse Ops", "WMS Routing", "Fleet Dispatch"],
        costRate: "$75/h",
        risk: "High",
        avatarText: "AR",
        avatarBg: "from-amber-600 to-orange-500",
        upcoming: "Overnight sorting window management",
        constraints: "Max 50h weekly overtime cap",
      },
      {
        id: "RT-02",
        name: "Priya Sharma",
        role: "Fulfillment Inventory Supervisor",
        type: "People",
        status: "High Load",
        utilization: 89,
        project: "High-Priority Pick Zone",
        skills: ["Barcode Scanning", "Pallet Loading", "SKU Reconciliation"],
        costRate: "$65/h",
        risk: "Medium",
        avatarText: "PS",
        avatarBg: "from-yellow-600 to-amber-500",
        upcoming: "Black Friday electronics order surge",
        constraints: "Zone A lock-in until 04:00 AM shift change",
      },
      {
        id: "RT-03",
        name: "Marcus Vance",
        role: "Fleet Maintenance & Forklift Lead",
        type: "People",
        status: "Available",
        utilization: 60,
        project: "Heavy Equipment Bay",
        skills: ["Forklift Operations", "EV Van Maintenance", "Battery Swaps"],
        costRate: "$70/h",
        risk: "Low",
        avatarText: "MV",
        avatarBg: "from-emerald-600 to-teal-500",
        upcoming: "Van fleet brake safety inspection",
        constraints: "On-call emergency road assist starts Friday",
      },
      {
        id: "RT-04",
        name: "Elena Rostova",
        role: "Quality Assurance & Packing Inspector",
        type: "People",
        status: "Available",
        utilization: 72,
        project: "Fragile Goods Packing",
        skills: ["Damage Inspection", "Customs Labeling", "Packaging"],
        costRate: "$55/h",
        risk: "Low",
        avatarText: "ER",
        avatarBg: "from-purple-600 to-pink-500",
        upcoming: "Luxury electronics packaging audits",
        constraints: "Cannot lift items exceeding 50 lbs",
      },
      {
        id: "RT-05",
        name: "Automated Sorting Conveyor 2",
        role: "High-Speed Optical Package Sorter",
        type: "Equipment",
        status: "High Load",
        utilization: 96,
        project: "Central Hub Alpha",
        skills: ["Laser Barcode Scanner", "Air-Jet Diverters"],
        costRate: "$120/h",
        risk: "High",
        avatarText: "SRT",
        avatarBg: "from-red-600 to-rose-500",
        upcoming: "Belt tension recalibration due in 48 hours",
        constraints: "Max sorting velocity 6,000 parcels/hour",
      },
      {
        id: "RT-06",
        name: "Electric Delivery Van Fleet",
        role: "24x Ford E-Transit Delivery Vans",
        type: "Equipment",
        status: "Available",
        utilization: 54,
        project: "Metro Last-Mile Delivery",
        skills: ["GPS Telematics", "Refrigerated Cargo Bay"],
        costRate: "$80/h",
        risk: "Low",
        avatarText: "VAN",
        avatarBg: "from-blue-600 to-cyan-500",
        upcoming: "11 vans open for emergency delivery runs",
        constraints: "DC Fast Charging required after 130 miles",
      },
      {
        id: "RT-07",
        name: "Seasonal Overtime & Driver Fund",
        role: "Expedited Courier Sourcing Pool",
        type: "Budget",
        status: "Available",
        utilization: 45,
        project: "Fulfillment Governance",
        skills: ["Temporary Staff Sourcing", "Third-Party Couriers"],
        costRate: "$4,500",
        risk: "Low",
        avatarText: "CAP",
        avatarBg: "from-green-600 to-emerald-500",
        upcoming: "$2,475 reserve buffer open",
        constraints: "Approved for seasonal peak windows only",
      },
      {
        id: "RT-08",
        name: "Pallet Buffer & Staging Bay",
        role: "High-Density Temperature-Controlled Racks",
        type: "Shared",
        status: "High Load",
        utilization: 88,
        project: "Staging Zone 4",
        skills: ["Cross-Docking", "Automated Retrieval (ASRS)"],
        costRate: "$35/h",
        risk: "Medium",
        avatarText: "STG",
        avatarBg: "from-orange-600 to-amber-600",
        upcoming: "Inbound semi-trailer transfer at midnight",
        constraints: "Max storage capacity 800 pallets",
      },
    ],
  },
  {
    id: "aviation",
    name: "Airlines & Airport Operations",
    category: "Aviation & Transport",
    organization: "Skyline Airways",
    icon: "✈️",
    accentColor: "#6366f1",
    criticalPathProduct: "Transcon Flight #412 & Hub Turnaround",
    incidentTitle: "Turnaround at Risk: Captain Flight Duty Time Expiry",
    incidentDetail:
      "Adverse headwinds delayed inbound Flight #408, causing Captain Arjun Rao to approach strict FAA 14-hour duty limits. Without immediate standby pilot reallocation, Flight #412 will cancel, stranding 240 passengers and cascading delays to 14 connecting aircraft.",
    incidentDelay: "+4.5 Hours",
    incidentCost: "$34,000",
    systemHealth: "89.1%",
    uptime: "99.92%",
    atRiskCapacity: "240 seats (B737-MAX8)",
    forecastConfidence: "95.5%",
    openDecisions: "2 decisions · 2 urgent",
    resources: [
      {
        id: "AV-01",
        name: "Captain Arjun Rao",
        role: "Senior Line Pilot (B737-MAX8)",
        type: "People",
        status: "Unavailable",
        utilization: 97,
        project: "Transcon Service Flight 412",
        skills: ["B737 Type Rating", "CAT III ILS", "CRM Command"],
        costRate: "$220/h",
        risk: "High",
        avatarText: "AR",
        avatarBg: "from-indigo-600 to-blue-500",
        upcoming: "Flight duty limit breaches in 48 minutes",
        constraints: "FAA mandatory 10h uninterrupted crew rest",
      },
      {
        id: "AV-02",
        name: "First Officer Priya Sharma",
        role: "Reserve First Officer (B737-800)",
        type: "People",
        status: "High Load",
        utilization: 84,
        project: "Airport Standby Crew",
        skills: ["B737 Type Rating", "ETOPS Operations", "Navigation"],
        costRate: "$145/h",
        risk: "Medium",
        avatarText: "PS",
        avatarBg: "from-blue-600 to-cyan-500",
        upcoming: "Available for immediate gate dispatch",
        constraints: "Needs captain-qualified line check observer",
      },
      {
        id: "AV-03",
        name: "Marcus Vance",
        role: "Ramp Operations & Ground Dispatch Lead",
        type: "People",
        status: "Available",
        utilization: 66,
        project: "Terminal 2 Ramp Control",
        skills: ["Pushback Tug Ops", "Baggage Loading", "Turnaround Timing"],
        costRate: "$65/h",
        risk: "Low",
        avatarText: "MV",
        avatarBg: "from-teal-600 to-emerald-500",
        upcoming: "Gate 14 rapid turnaround supervision",
        constraints: "On-call overnight shift starts Friday",
      },
      {
        id: "AV-04",
        name: "Elena Rostova",
        role: "Lead Flight Dispatcher & Meteorologist",
        type: "People",
        status: "Available",
        utilization: 70,
        project: "Flight Operations Control",
        skills: ["Fuel Calculations", "Weather Routing", "FAA Flight Filing"],
        costRate: "$85/h",
        risk: "Low",
        avatarText: "ER",
        avatarBg: "from-purple-600 to-pink-500",
        upcoming: "Clear-air turbulence alternate flight plans",
        constraints: "Manages 18 simultaneous active flights",
      },
      {
        id: "AV-05",
        name: "Gate 14 Jetbridge & Stand",
        role: "Widebody Turnaround Gate Slot",
        type: "Equipment",
        status: "High Load",
        utilization: 95,
        project: "Terminal 2 Hub",
        skills: ["400Hz Ground Power", "Pre-conditioned Air", "Dual Jetbridge"],
        costRate: "$350/h",
        risk: "High",
        avatarText: "G14",
        avatarBg: "from-rose-600 to-red-500",
        upcoming: "Next international flight arrival in 45m",
        constraints: "Airport slot penalties accrued if ground time > 50m",
      },
      {
        id: "AV-06",
        name: "Aircraft De-Icing Truck Alpha",
        role: "Type IV Anti-Icing Fluid Rig",
        type: "Equipment",
        status: "Available",
        utilization: 45,
        project: "Winter Weather Ops",
        skills: ["Forced Air De-icing", "Glycol Spray Boom"],
        costRate: "$150/h",
        risk: "Low",
        avatarText: "ICE",
        avatarBg: "from-cyan-500 to-blue-600",
        upcoming: "Standby for incoming winter freeze front",
        constraints: "Heated fluid tanks require 30m prep cycle",
      },
      {
        id: "AV-07",
        name: "Passenger Reaccommodation Reserve",
        role: "Hotel & Voucher Emergency Fund",
        type: "Budget",
        status: "Available",
        utilization: 40,
        project: "Customer Experience",
        skills: ["Hotel Vouchers", "Interline Partner Rebooking"],
        costRate: "$8,000",
        risk: "Low",
        avatarText: "PAX",
        avatarBg: "from-green-600 to-emerald-500",
        upcoming: "$4,800 contingency buffer remaining",
        constraints: "Mandated by FAA Passenger Bill of Rights",
      },
      {
        id: "AV-08",
        name: "Hydrant Jet-A Fueling Network",
        role: "Underground High-Pressure Fuel Feed",
        type: "Shared",
        status: "High Load",
        utilization: 86,
        project: "Fuel Farm",
        skills: ["1,000 gpm Pumping", "Fuel Testing & Quality Check"],
        costRate: "$4.10/gal",
        risk: "Medium",
        avatarText: "JETA",
        avatarBg: "from-orange-600 to-amber-600",
        upcoming: "Refueling scheduled at T-minus 25 minutes",
        constraints: "Zero mobile phone / RF emissions during pumping",
      },
    ],
  },
  {
    id: "construction",
    name: "Construction & Infrastructure",
    category: "Engineering & Civil",
    organization: "Titan Mega-Infrastructure",
    icon: "🏗️",
    accentColor: "#ea580c",
    criticalPathProduct: "Metro Rail Viaduct Foundation Pour",
    incidentTitle: "Foundation at Risk: Structural Inspector Absence",
    incidentDetail:
      "A certified seismic structural inspector is absent prior to a 400-cubic-meter continuous concrete pour. Without verification by 10:00 AM, 18 concrete trucks will idle ($500/h fee), city road-closure permits will expire, and the pier foundation slips by 14 days.",
    incidentDelay: "+14 Days",
    incidentCost: "$42,000",
    systemHealth: "82.5%",
    uptime: "99.40%",
    atRiskCapacity: "400 m³ Concrete Pour",
    forecastConfidence: "91.8%",
    openDecisions: "3 decisions · 2 urgent",
    resources: [
      {
        id: "CN-01",
        name: "Arjun Rao",
        role: "Lead Seismic Structural Inspector",
        type: "People",
        status: "Unavailable",
        utilization: 95,
        project: "Pier 14 Foundation Inspection",
        skills: ["Seismic Rebar Audit", "NDT Ultrasonic Testing", "OSHA Sign-off"],
        costRate: "$130/h",
        risk: "High",
        avatarText: "AR",
        avatarBg: "from-orange-600 to-amber-500",
        upcoming: "Pre-pour rebar cage inspection required",
        constraints: "Must hold State PE Civil License for sign-off",
      },
      {
        id: "CN-02",
        name: "Priya Sharma",
        role: "Civil Structural Project Engineer",
        type: "People",
        status: "High Load",
        utilization: 87,
        project: "North Viaduct Segment",
        skills: ["BIM 3D", "Structural Calculations", "Permit Approvals"],
        costRate: "$115/h",
        risk: "Medium",
        avatarText: "PS",
        avatarBg: "from-amber-600 to-yellow-500",
        upcoming: "Assistant inspector dual verification",
        constraints: "Managing concurrent tunnel boring reports",
      },
      {
        id: "CN-03",
        name: "Marcus Vance",
        role: "Heavy Tower Crane Operator",
        type: "People",
        status: "Available",
        utilization: 64,
        project: "Main Pier Crane Rig",
        skills: ["150-Ton Crane", "Tandem Rigging", "Wind Gauge Monitoring"],
        costRate: "$95/h",
        risk: "Low",
        avatarText: "MV",
        avatarBg: "from-emerald-600 to-teal-500",
        upcoming: "Concrete bucket lifting operations",
        constraints: "Operations halted if wind exceeds 28 mph",
      },
      {
        id: "CN-04",
        name: "Elena Rostova",
        role: "Environmental & Concrete Quality Tech",
        type: "People",
        status: "Available",
        utilization: 70,
        project: "Field Testing Lab",
        skills: ["Concrete Slump Test", "Curing Compressive Strength", "Air Entrainment"],
        costRate: "$80/h",
        risk: "Low",
        avatarText: "ER",
        avatarBg: "from-purple-600 to-pink-500",
        upcoming: "Batch 4 slump & temperature verification",
        constraints: "Lab samples require 24h water bath incubation",
      },
      {
        id: "CN-05",
        name: "150-Ton Crawler Crane Alpha",
        role: "Heavy Lift Lattice Boom Rig",
        type: "Equipment",
        status: "High Load",
        utilization: 94,
        project: "Viaduct Pier 14",
        skills: ["Heavy Rigging", "180ft Radius Reach"],
        costRate: "$380/h",
        risk: "High",
        avatarText: "CRN",
        avatarBg: "from-red-600 to-rose-500",
        upcoming: "Continuous 8-hour placement cycle",
        constraints: "Daily mechanical hydraulic check mandatory",
      },
      {
        id: "CN-06",
        name: "Ready-Mix Concrete Fleet",
        role: "18x Transit Mixer Trucks",
        type: "Equipment",
        status: "Available",
        utilization: 55,
        project: "Continuous Pour Logistics",
        skills: ["Rotating Drum", "Chute Extenders", "Slump Preservation"],
        costRate: "$140/h",
        risk: "Low",
        avatarText: "MIX",
        avatarBg: "from-blue-600 to-cyan-500",
        upcoming: "En route from batch plant 4 miles away",
        constraints: "Concrete must be placed within 90m of batching",
      },
      {
        id: "CN-07",
        name: "Civil Delay Penalty Contingency",
        role: "Contractual Liquidated Damages Buffer",
        type: "Budget",
        status: "Available",
        utilization: 35,
        project: "Metro Authority Contract",
        skills: ["City Permit Extension", "Emergency Overtime Shifts"],
        costRate: "$15,000",
        risk: "Low",
        avatarText: "BUD",
        avatarBg: "from-green-600 to-emerald-500",
        upcoming: "$9,750 unallocated penalty buffer",
        constraints: "City fines accrue at $2,000/hr past curfew",
      },
      {
        id: "CN-08",
        name: "Municipal Lane Closure Permit",
        role: "Approved Highway Traffic Reroute",
        type: "Shared",
        status: "High Load",
        utilization: 90,
        project: "Traffic Control Department",
        skills: ["Police Escort", "Variable Message Road Signs"],
        costRate: "$250/h",
        risk: "High",
        avatarText: "DOT",
        avatarBg: "from-orange-600 to-amber-600",
        upcoming: "Permit expires sharply at 16:00 PM today",
        constraints: "Strict non-negotiable city lane clearance deadline",
      },
    ],
  },
  {
    id: "trading",
    name: "Quantitative Trading & Hedge Funds",
    category: "Financial Markets",
    organization: "Apex Capital Strategies",
    icon: "📈",
    accentColor: "#8b5cf6",
    criticalPathProduct: "Algorithmic Market-Making & Risk Limits",
    incidentTitle: "Risk Limits at Risk: Quantitative Risk Officer Offline",
    incidentDetail:
      "High market volatility at market open has coincided with the sudden absence of the Lead Risk Officer. Real-time portfolio Value-at-Risk (VaR) calculations are stalling, forcing circuit-breaker trade restrictions that risk $58,000 in unhedged index exposures.",
    incidentDelay: "+3.2 Hours",
    incidentCost: "$58,000",
    systemHealth: "92.8%",
    uptime: "99.999%",
    atRiskCapacity: "$12.4M Portfolio VaR",
    forecastConfidence: "97.1%",
    openDecisions: "4 decisions · 2 urgent",
    resources: [
      {
        id: "TD-01",
        name: "Arjun Rao",
        role: "Chief Quantitative Risk Officer",
        type: "People",
        status: "Unavailable",
        utilization: 98,
        project: "Global Equity Derivatives Desk",
        skills: ["Monte-Carlo VaR", "Options Greeks", "SEC Capital Rules"],
        costRate: "$320/h",
        risk: "High",
        avatarText: "AR",
        avatarBg: "from-purple-600 to-indigo-500",
        upcoming: "Volatility circuit breaker sign-off",
        constraints: "Sole authorized officer for limit overrides",
      },
      {
        id: "TD-02",
        name: "Priya Sharma",
        role: "Senior High-Frequency Algorithmic Trader",
        type: "People",
        status: "High Load",
        utilization: 88,
        project: "US Index ETF Execution",
        skills: ["C++ Low Latency", "Order Book Arbitrage", "Dark Pools"],
        costRate: "$260/h",
        risk: "Medium",
        avatarText: "PS",
        avatarBg: "from-indigo-600 to-blue-500",
        upcoming: "Market opening bell order book stabilization",
        constraints: "Requires dual confirmation for gross trades > $5M",
      },
      {
        id: "TD-03",
        name: "Marcus Vance",
        role: "Ultra-Low-Latency Network Architect",
        type: "People",
        status: "Available",
        utilization: 62,
        project: "Colocation Datacenter Secaucus",
        skills: ["Kernel Bypass (Solarflare)", "10GbE PTP Time-sync", "FPGA"],
        costRate: "$180/h",
        risk: "Low",
        avatarText: "MV",
        avatarBg: "from-teal-600 to-emerald-500",
        upcoming: "Direct CME exchange feed latency tuning",
        constraints: "On-call overnight trading desk begins Friday",
      },
      {
        id: "TD-04",
        name: "Elena Rostova",
        role: "Regulatory Compliance & SEC Auditor",
        type: "People",
        status: "Available",
        utilization: 70,
        project: "FINRA & Trade Surveillance",
        skills: ["Market Abuse Detection", "Rule 15c3-5", "Audit Trails"],
        costRate: "$150/h",
        risk: "Low",
        avatarText: "ER",
        avatarBg: "from-pink-600 to-purple-500",
        upcoming: "End-of-day SEC regulatory trade filings",
        constraints: "Mandatory compliance review window",
      },
      {
        id: "TD-05",
        name: "FPGA Algorithmic Execution Core",
        role: "Sub-Microsecond Xilinx Hardware Rack",
        type: "Equipment",
        status: "High Load",
        utilization: 97,
        project: "Secaucus Colocation",
        skills: ["Hardware VHDL", "Direct Market Access", "Sub-microsecond"],
        costRate: "$400/h",
        risk: "High",
        avatarText: "FPGA",
        avatarBg: "from-red-600 to-rose-500",
        upcoming: "Zero-loss packet parsing evaluation",
        constraints: "Chamber temperature threshold maximum 72°C",
      },
      {
        id: "TD-06",
        name: "Direct OPRA Options Market Feed",
        role: "Consolidated Real-Time Quote Stream",
        type: "Equipment",
        status: "Available",
        utilization: 52,
        project: "Exchange Connectivity",
        skills: ["Multicast Tick Stream", "40Gbps Ingestion"],
        costRate: "$210/h",
        risk: "Low",
        avatarText: "TICK",
        avatarBg: "from-blue-600 to-cyan-500",
        upcoming: "100% feed redundancy verified",
        constraints: "Bandwidth surge capacity up to 80 Gbps",
      },
      {
        id: "TD-07",
        name: "Intraday Clearing Margin Buffer",
        role: "DTCC Capital Liquidity Reserve",
        type: "Budget",
        status: "Available",
        utilization: 45,
        project: "Treasury Management",
        skills: ["Fedwire Settlement", "Collateral Optimization"],
        costRate: "$50,000",
        risk: "Low",
        avatarText: "MARG",
        avatarBg: "from-green-600 to-emerald-500",
        upcoming: "$27,500 unencumbered collateral buffer",
        constraints: "Requires Chief Financial Officer authorization",
      },
      {
        id: "TD-08",
        name: "Exchange Dark Pool Liquidity Router",
        role: "Cross-Venue Smart Order Gateway",
        type: "Shared",
        status: "High Load",
        utilization: 85,
        project: "Execution Venues",
        skills: ["VWAP Execution", "Anti-Gaming Algorithms"],
        costRate: "$45/h",
        risk: "Medium",
        avatarText: "DARK",
        avatarBg: "from-orange-600 to-amber-600",
        upcoming: "Midpoint liquidity matching active",
        constraints: "Order size capped under 50,000 shares per slice",
      },
    ],
  },
];
